spring:
  application:
    name: Kafka Event Driven Architecture Task
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    device-metrics:
      name: device-metrics
      partitions: 3 # amount of partitions
      replicas: 1 # amount of replicas
      retention: 2629746000 # amount of time data will be stored in the topic. Unit: ms.  2629746000 = 1 month
    device-sessions:
      name: device-sessions
      partitions: 3
      replicas: 1
      retention: 2629746000
    game-sessions:
      name: game-sessions
      partitions: 3
      replicas: 1
      retention: 2629746000

